version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    # depends_on:
    #   - mongo

#   frontend:
#     build: ./frontend
#     container_name: frontend_service
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - backend

# volumes:
#   mongo_data:
