version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - mongo

#   frontend:
#     build: ./frontend
#     container_name: frontend_service
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - backend

#   mongo:
#     image: mongo
#     container_name: mongo_service
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:
