version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env

  frontend:
    image: node:18
    container_name: frontend_service
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
